apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: 462270994088.dkr.ecr.us-east-1.amazonaws.com/web_repo:V0.2
        env:
        - name: DBHOST
          value: "mysql.mysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "5295"
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
