apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: employees
spec:
  containers:
  - name: web
    image: "462270994088.dkr.ecr.us-east-1.amazonaws.com/web_repo:V0.1"
    env:
    - name: DBHOST
      value: "mysql.mysql.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: MYSQL_ROOT_PASSWORD
      value: "5295"
    ports:
    - containerPort: 8080